pipeline{
    agent any
    stages {
        stage('Get source') {
            steps {
                echo 'getting source'
                checkout scm
   
            }
        }
        stage('running php-apache'){
            steps{
                echo 'run php-apache docker image'           
                sh 'docker service create  -p 80:80 --name task-2-apache --mount type=bind,source=/var/www/html,target=/var/www/html php:7.0-apache' 
            }
        }

    }
}

